version: "3.8"

services:
   backend:
      build: ../backend
      container_name: movapp-backend
      ports:
         - "5005:3005"
      env_file:
         - ../backend/.env.docker
      environment:
         - TZ=America/Mexico_City
      depends_on:
         db:
            condition: service_healthy
      networks:
         - movapp-network
      restart: unless-stopped

   backoffice-backend:
      build: ../backoffice-backend
      container_name: movapp-backoffice-backend
      ports:
         - "5006:3006"
      env_file:
         - ../backoffice-backend/.env.docker
      environment:
         - TZ=America/Mexico_City
      depends_on:
         db:
            condition: service_healthy
      networks:
         - movapp-network
      restart: unless-stopped

   db:
      image: postgres:16
      container_name: movapp-db
      restart: always
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: movapp
         POSTGRES_DB: Movapp
         TZ: America/Mexico_City
         PGTZ: America/Mexico_City
      ports:
         - "5432:5432"
      volumes:
         - movapp_db_data:/var/lib/postgresql/data
         - ../init-db:/docker-entrypoint-initdb.d
         - /etc/localtime:/etc/localtime:ro
      command: postgres -c timezone=America/Mexico_City
      networks:
         - movapp-network
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U admin -d Movapp"]
         interval: 10s
         timeout: 5s
         retries: 5

volumes:
   movapp_db_data:

networks:
   movapp-network:
      name: movapp-network
      driver: bridge
